# Generated by Django 5.0.6 on 2024-06-02 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100)),
                ('fio', models.CharField(help_text='Familiya, Ism, Otasining ismi', max_length=30, verbose_name='FIO')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=250, verbose_name='Project Name')),
                ('tel_number', models.CharField(help_text='Contact telephone number', max_length=20, verbose_name='Telephone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ma'lumot",
                'verbose_name_plural': "Ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='DocsData6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document6', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Anotatsiya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maindata')),
            ],
            options={
                'verbose_name': 'Anotatsiya',
                'verbose_name_plural': 'Anotatsiyalar',
            },
        ),
        migrations.CreateModel(
            name='DocsData5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document5', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Loyiha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maindata')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='DocsData4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document4', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Taqriz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maindata')),
            ],
            options={
                'verbose_name': 'Taqriz',
                'verbose_name_plural': 'Taqrizlar',
            },
        ),
        migrations.CreateModel(
            name='DocsData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document3', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Raxbar mulohazasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maindata')),
            ],
            options={
                'verbose_name': 'Raxbar mulohazasi',
                'verbose_name_plural': 'Raxbar mulohazalari',
            },
        ),
        migrations.CreateModel(
            name='DocsData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document2', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='BMI hisoboti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maindata')),
            ],
            options={
                'verbose_name': 'BMI hisoboti',
                'verbose_name_plural': 'BMI hisobotlari',
            },
        ),
        migrations.CreateModel(
            name='DocsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Taqdimot fayli')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maindata')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
            },
        ),
    ]
